import { ChampionshipData } from './types';

export const mockData: ChampionshipData = {
  drivers: [
    { id: 'd1', name: 'Max Verstappen', team: 'Red Bull Racing', teamColor: '#1e41ff', points: 85 },
    { id: 'd2', name: 'Charles Leclerc', team: 'Ferrari', teamColor: '#ff2800', points: 78 },
    { id: 'd3', name: 'Lando Norris', team: 'McLaren', teamColor: '#ff8000', points: 65 },
    { id: 'd4', name: 'Fernando Alonso', team: 'Aston Martin', teamColor: '#006f62', points: 45 },
    { id: 'd5', name: 'Lewis Hamilton', team: 'Mercedes', teamColor: '#00d2be', points: 40 },
    { id: 'd6', name: 'Oscar Piastri', team: 'McLaren', teamColor: '#ff8000', points: 38 },
    { id: 'd7', name: 'Carlos Sainz', team: 'Ferrari', teamColor: '#ff2800', points: 35 },
    { id: 'd8', name: 'Sergio Perez', team: 'Red Bull Racing', teamColor: '#1e41ff', points: 30 },
  ],
  constructors: [
    { id: 'c1', name: 'Red Bull Racing', color: '#1e41ff', points: 115 },
    { id: 'c2', name: 'Ferrari', color: '#ff2800', points: 113 },
    { id: 'c3', name: 'McLaren', color: '#ff8000', points: 103 },
    { id: 'c4', name: 'Aston Martin', color: '#006f62', points: 45 },
    { id: 'c5', name: 'Mercedes', color: '#00d2be', points: 40 },
  ],
  races: [
    {
      id: 'r1',
      name: 'Bahrain Grand Prix',
      circuit: 'Bahrain International Circuit',
      date: '2024-03-02',
      status: 'completed',
      polePosition: 'd1',
      results: [
        { driverId: 'd1', position: 1, points: 25, fastestLap: true, dnf: false },
        { driverId: 'd2', position: 2, points: 18, fastestLap: false, dnf: false },
        { driverId: 'd3', position: 3, points: 15, fastestLap: false, dnf: false },
        { driverId: 'd4', position: 4, points: 12, fastestLap: false, dnf: false },
        { driverId: 'd5', position: 5, points: 10, fastestLap: false, dnf: false },
        { driverId: 'd6', position: 6, points: 8, fastestLap: false, dnf: false },
        { driverId: 'd7', position: 7, points: 6, fastestLap: false, dnf: false },
        { driverId: 'd8', position: 8, points: 4, fastestLap: false, dnf: false },
      ],
    },
    {
      id: 'r2',
      name: 'Saudi Arabian Grand Prix',
      circuit: 'Jeddah Corniche Circuit',
      date: '2024-03-09',
      status: 'completed',
      polePosition: 'd2',
      results: [
        { driverId: 'd2', position: 1, points: 25, fastestLap: false, dnf: false },
        { driverId: 'd1', position: 2, points: 18, fastestLap: true, dnf: false },
        { driverId: 'd3', position: 3, points: 15, fastestLap: false, dnf: false },
        { driverId: 'd6', position: 4, points: 12, fastestLap: false, dnf: false },
        { driverId: 'd5', position: 5, points: 10, fastestLap: false, dnf: false },
        { driverId: 'd4', position: 6, points: 8, fastestLap: false, dnf: false },
        { driverId: 'd7', position: 7, points: 6, fastestLap: false, dnf: false },
        { driverId: 'd8', position: 8, points: 4, fastestLap: false, dnf: false },
      ],
    },
    {
      id: 'r3',
      name: 'Australian Grand Prix',
      circuit: 'Albert Park Circuit',
      date: '2024-03-24',
      status: 'completed',
      polePosition: 'd3',
      results: [
        { driverId: 'd3', position: 1, points: 25, fastestLap: true, dnf: false },
        { driverId: 'd2', position: 2, points: 18, fastestLap: false, dnf: false },
        { driverId: 'd1', position: 3, points: 15, fastestLap: false, dnf: false },
        { driverId: 'd4', position: 4, points: 12, fastestLap: false, dnf: false },
        { driverId: 'd5', position: 5, points: 10, fastestLap: false, dnf: false },
        { driverId: 'd6', position: 6, points: 8, fastestLap: false, dnf: false },
        { driverId: 'd7', position: 7, points: 6, fastestLap: false, dnf: false },
        { driverId: 'd8', position: 8, points: 4, fastestLap: false, dnf: false },
      ],
    },
    {
      id: 'r4',
      name: 'Japanese Grand Prix',
      circuit: 'Suzuka International Racing Course',
      date: '2024-04-07',
      status: 'pending',
    },
    {
      id: 'r5',
      name: 'Chinese Grand Prix',
      circuit: 'Shanghai International Circuit',
      date: '2024-04-21',
      status: 'pending',
    },
  ],
};
